language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '12'
  - '11'
  - '10'
  - '9'
  - '8'
before_script:
  - npm run build
after_success:
  - npm run coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: release
      node_js: lts/*
      script: echo "Deploying to npm ..."
      script:
        - npm run semantic-release
